# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.6
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Product Information Management.
repo_name: PIM
repo_slug: odoo-pim
travis_apt_packages: []
travis_apt_sources: []
