from . import test_char
from . import test_boolean
from . import test_char_translate
from . import test_float
from . import test_integer
from . import test_monetary
from . import test_selection
from . import test_text
from . import test_text_translate
from . import test_default_search_translate
