[project]
name = "odoo-addons-oca-odoo-pim"
version = "19.0.20260410.3"
dependencies = [
    "odoo-addon-attribute_set==19.0.*",
    "odoo-addon-pim==19.0.*",
    "odoo-addon-product_attribute_set==19.0.*",
    "odoo-addon-website_attribute_set==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
